export default {
  url: "https://hpgm-dashboard-production.eu-west-1.csq.io/dashboard/v2/distribution",
  name: "Request 3 - Disneylandparis - 2 goals",

  payload: {
    projectId: 788,
    from: "2022-12-17T11:00:00Z",
    to: "2023-01-16T10:06:50Z",
    deviceId: 1,
    segment: {
      nodeType: "OR",
      children: [
        {
          nodeType: "filter",
          field: "goal",
          operator: "equals",
          value: {
            action: "pageview",
            page: {
              nodeType: "AND",
              children: [
                {
                  field: "page:customVarValue1",
                  operator: "starts_with",
                  value: "dlrp:",
                  displayValue: "",
                  nodeType: "filter",
                },
                {
                  nodeType: "filter",
                  operator: "not_equals",
                  field: "page:customVarValue1",
                  value: "dlrp:content:home",
                  displayValue: "",
                },
                {
                  nodeType: "filter",
                  operator: "not_equals",
                  field: "page:customVarValue1",
                  value: "dlrp:offers:_index_spofpage",
                  displayValue: "",
                },
                {
                  nodeType: "filter",
                  operator: "not_starts_with",
                  field: "page:customVarValue1",
                  value: "dlrp:my",
                  displayValue: "",
                },
                {
                  nodeType: "filter",
                  operator: "not_starts_with",
                  field: "page:customVarValue1",
                  value: "dlrp:offers:package",
                  displayValue: "",
                },
                {
                  nodeType: "filter",
                  operator: "not_starts_with",
                  field: "page:customVarValue1",
                  value: "dlrp:tools:finder:destination",
                  displayValue: "",
                },
                {
                  nodeType: "filter",
                  operator: "not_starts_with",
                  field: "page:customVarValue1",
                  value: "dlrp:offers:ticket:",
                  displayValue: "",
                },
                {
                  nodeType: "filter",
                  operator: "not_equals",
                  field: "page:customVarValue1",
                  value: "dlrp:offers:tickets:fastpass",
                  displayValue: "",
                },
                {
                  nodeType: "filter",
                  operator: "not_starts_with",
                  field: "page:customVarValue1",
                  value: "dlrp:annual-passports:",
                  displayValue: "",
                },
                {
                  nodeType: "filter",
                  operator: "starts_with",
                  field: "page:customVarValue1",
                  value: "dlrp:tools:finder:resorts",
                  displayValue: "",
                },
              ],
            },
          },
        },
        {
          nodeType: "filter",
          field: "goal",
          operator: "equals",
          value: {
            action: "pageview",
            page: {
              nodeType: "OR",
              children: [
                {
                  nodeType: "AND",
                  children: [
                    {
                      field: "page:customVarValue4",
                      operator: "equals",
                      value: "fr",
                      nodeType: "filter",
                    },
                    {
                      field: "page:path",
                      operator: "not_contains",
                      value: "en-us",
                      displayValue: "",
                      nodeType: "filter",
                    },
                    {
                      nodeType: "filter",
                      operator: "equals",
                      field: "page:host",
                      value: "www.disneylandparis.com",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_ends_with",
                      field: "page:path",
                      value: "/offres/",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_equals",
                      field: "page:path",
                      value: "/fr-idf/hotels/",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_equals",
                      field: "page:path",
                      value: "/fr-fr/hotels/",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "services",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_ends_with",
                      field: "page:path",
                      value: "/aide/",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "offres/index",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_ends_with",
                      field: "page:path",
                      value: "fr-fr/",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_equals",
                      field: "page:path",
                      value: "/fr-idf/",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "horaires-parcs",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "restaurants",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "my-disneyland",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "attractions",
                    },
                    {
                      nodeType: "filter",
                      operator: "contains",
                      field: "page:path",
                      value: "hotels",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "chambres",
                      displayValue: "",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "/loisirs/",
                      displayValue: "",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "equi",
                      displayValue: "",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "faq",
                      displayValue: "",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "carte",
                      displayValue: "",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_equals",
                      field: "page:path",
                      value: "/fr-fr/hotels/fr-fr/hotels/",
                    },
                  ],
                },
                {
                  nodeType: "AND",
                  children: [
                    {
                      field: "page:customVarValue4",
                      operator: "equals",
                      value: "fr",
                      nodeType: "filter",
                    },
                    {
                      field: "page:path",
                      operator: "not_contains",
                      value: "en-us",
                      displayValue: "",
                      nodeType: "filter",
                    },
                    {
                      nodeType: "filter",
                      operator: "equals",
                      field: "page:host",
                      value: "www.disneylandparis.com",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_ends_with",
                      field: "page:path",
                      value: "/offres/",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_equals",
                      field: "page:path",
                      value: "/fr-idf/hotels/",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_equals",
                      field: "page:path",
                      value: "/fr-fr/hotels/",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "services",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_ends_with",
                      field: "page:path",
                      value: "/aide/",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "offres/index",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_ends_with",
                      field: "page:path",
                      value: "fr-fr/",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_equals",
                      field: "page:path",
                      value: "/fr-idf/",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "horaires-parcs",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "restaurants",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "my-disneyland",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "attractions",
                    },
                    {
                      nodeType: "filter",
                      operator: "contains",
                      field: "page:path",
                      value: "hotels",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "chambres",
                      displayValue: "",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "/loisirs/",
                      displayValue: "",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "equi",
                      displayValue: "",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "faq",
                      displayValue: "",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "carte",
                      displayValue: "",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_is_empty",
                      field: "page:query",
                      value: "",
                    },
                  ],
                },
                {
                  nodeType: "AND",
                  children: [
                    {
                      field: "page:customVarValue4",
                      operator: "equals",
                      value: "fr",
                      nodeType: "filter",
                    },
                    {
                      field: "page:path",
                      operator: "not_contains",
                      value: "en-us",
                      displayValue: "",
                      nodeType: "filter",
                    },
                    {
                      nodeType: "filter",
                      operator: "equals",
                      field: "page:host",
                      value: "www.disneylandparis.com",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_ends_with",
                      field: "page:path",
                      value: "/offres/",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_equals",
                      field: "page:path",
                      value: "/fr-idf/hotels/",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_equals",
                      field: "page:path",
                      value: "/fr-fr/hotels/",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "comment",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_ends_with",
                      field: "page:path",
                      value: "/aide/",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "offres/index",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_ends_with",
                      field: "page:path",
                      value: "fr-fr/",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_equals",
                      field: "page:path",
                      value: "/fr-idf/",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "horaires-parcs",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "restaurants",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "my-disneyland",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "attractions",
                    },
                    {
                      nodeType: "filter",
                      operator: "contains",
                      field: "page:path",
                      value: "hotels",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "chambres",
                      displayValue: "",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "/loisirs/",
                      displayValue: "",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "equi",
                      displayValue: "",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "faq",
                      displayValue: "",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "carte",
                      displayValue: "",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_equals",
                      field: "page:path",
                      value: "/fr-fr/hotels/fr-fr/hotels/",
                    },
                  ],
                },
                {
                  nodeType: "AND",
                  children: [
                    {
                      field: "page:customVarValue4",
                      operator: "equals",
                      value: "fr",
                      nodeType: "filter",
                    },
                    {
                      field: "page:path",
                      operator: "not_contains",
                      value: "en-us",
                      displayValue: "",
                      nodeType: "filter",
                    },
                    {
                      nodeType: "filter",
                      operator: "equals",
                      field: "page:host",
                      value: "www.disneylandparis.com",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_ends_with",
                      field: "page:path",
                      value: "/offres/",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_equals",
                      field: "page:path",
                      value: "/fr-idf/hotels/",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_equals",
                      field: "page:path",
                      value: "/fr-fr/hotels/",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "comment",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_ends_with",
                      field: "page:path",
                      value: "/aide/",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "offres/index",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_ends_with",
                      field: "page:path",
                      value: "fr-fr/",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_equals",
                      field: "page:path",
                      value: "/fr-idf/",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "horaires-parcs",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "restaurants",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "my-disneyland",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "attractions",
                    },
                    {
                      nodeType: "filter",
                      operator: "contains",
                      field: "page:path",
                      value: "hotels",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "chambres",
                      displayValue: "",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "/loisirs/",
                      displayValue: "",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "equi",
                      displayValue: "",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "faq",
                      displayValue: "",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_contains",
                      field: "page:path",
                      value: "carte",
                      displayValue: "",
                    },
                    {
                      nodeType: "filter",
                      operator: "not_is_empty",
                      field: "page:query",
                      value: "",
                    },
                  ],
                },
              ],
            },
          },
        },
      ],
    },
    dimension: "os",
  },
};
